defaults:
    - base_scheduler
    - _self_

# scheduler to use for updating learning rate
type: "StepLR"

# number of epochs between each decay step
step_size: 2

# multiplicative factor of learning rate decay
gamma: 0.984

# warmup scheduler settings
warmup:
    use: true  # use warmup
    multiplier: 1.0
    total_epoch: 20  # perform warmup throughout first 10 epochs